### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by edalorzo** [sdeleuze/spring-reactive-playground#12]
There's a couple of configuration issues from using the code out the box.

The first is that in `PostgresConfiguration` the `username` is hardcoded to `"seb"` instead of coming from the configuration file `application.properties`.

The second is that the POST request fails with a 

```
Request failure [status: 415, reason: "Content type 'application/json' not supported"]
```

I suppose the JSON support is not properly configured in the example.

I managed to solve the JSON problem by doing

``` java
List<HttpMessageConverter<?>> converters =
            Arrays.asList(new ResourceHttpMessageConverter(),
                new CodecHttpMessageConverter<Object>(new JacksonJsonEncoder(), new JacksonJsonDecoder()),
                new CodecHttpMessageConverter<String>(new StringEncoder(), new StringDecoder()));

handlerAdapter.setMessageConverters(converters);
```

However, the POST request only accepts a single `Person` at the time, and not as the `Flux<Person>` and the documentation seem to suggest that it could also accept an array of them.

In this case I got a `JsonMappingException: Can not deserialize instance of playground.Person out of START_ARRAY token` because the mapper is trying to get `Person` type out of the JSON string.

**Comment by sdeleuze** [comment]
Thanks for your feedback, I am going to have to look to these issues.

**Comment by sdeleuze** [comment]
Not relevant anymore since SQL database support is out of the scope for now. We will use NoSQL datastore supported by the upcoming Spring Data Reactive support (Mongo, Redis, Cassandra). SQL support will be evaluated later.
