### ISSUE TITLE
Update for Spring 5 Build Snapshot that includes reactive support

### ISSUE THREAD

**Issue by geoand** [sdeleuze/spring-reactive-playground#14]
This repo seems to me that it serves as the canonical example of how Spring with reactive support looks like.
It would be great if it could be updated to use latest Spring 5 build snapshot that includes Reactive support.

Or perhaps is there some example inside the Spring Framework repository that better serves the purpose of demonstrating Spring's reactive capabilities? 

Thanks!

**Comment by sdeleuze** [comment]
Done :-)

**Comment by geoand** [comment]
Awesome!

Thanks!
